### PR TITLE
Add dark mode/light theme - Vanilla.js #84

### PR DESCRIPTION
**Pull request by 29deepanshutyagi**
issue #84

### CODE REVIEW

**Comment by 29deepanshutyagi** [comment]
and kindly labelled this issue as large instead of medium, as it's consist of various tasks

**Comment by taniashiba** [comment]
> and kindly labelled this issue as large instead of medium, as it's consist of various tasks

Hi there, thank you for sharing your PR! Our team will review it soon, and we will make sure to review and assign the weight according to our team. Thank you for your contribution! ❤️

**Comment by blackgirlbytes** [comment]
Thanks for the contribution!
hmm @29deepanshutyagi what various tasks? let me know. It seems like you added tests and added dark mode/light mode which is required of the ticket. 

Very similar to this issue -- which has 30 files changed adding dark mode and light mode for Vue project. It was weighed at medium https://github.com/TBD54566975/tbd-examples/pull/176

**Comment by 29deepanshutyagi** [comment]
Theme Toggle Button:

    Created a toggle button in main.js to switch between dark and light themes, ensuring it is always present in the UI.

Local Storage Integration:

    Implemented functionality to store the user's theme preference in localStorage, allowing the theme choice to persist across sessions.

Theme Application:

    Added logic to apply the selected theme (dark or light) to the entire application based on the user's choice.

Default Theme Handling:

    Set the application to default to the system’s theme preference if no theme is stored in localStorage.

End-to-End Testing:

    Created end-to-end tests using Playwright to verify that the theme toggle functionality works correctly, including:
        Correct application of the selected theme.
        Persistence of theme preference across page refreshes and sessions.
        Appropriate loading of themes based on localStorage.

**Comment by 29deepanshutyagi** [comment]
kindly tell me , if there is any issue in this pr

**Comment by blackgirlbytes** [comment]
@29deepanshutyagi I updated your PR to be a large, but I had to label the Vue version of this ticket as a large as well. To be fair.

**Review by blackgirlbytes — APPROVED** [review]
Looks good!

**Pull request merged**
