### PR TITLE
DWA Starter: Create basic "Hello World" Vanilla.js app

### LINKED ISSUE #82: Create basic "Hello World" Vanilla.js app
## 🚀  Goal
Set up a basic Vanilla.js project structure and create a simple application that renders the words "Hello World" on the screen. This will serve as the foundation for our Decentralized Web App (DWA) starter in Vanilla.

## 🤔 Background
We're expanding our DWA starter collection to include Vanilla.js. This task is the first step in creating a Vanilla.js version of our DWA starter app, which will help developers kickstart their Web5 projects using Vanilla.

> This is part of our larger project to create a Vanilla.js DWA starter. See our [main issue here](https://github.com/TBD54566975/tbd-examples/issues/81) for the full context and list of all related tasks.

## 🔑  Tasks and Acceptance Criteria

- [ ] Set up a new Vanilla.js project using Vanilla CLI or Vite
- [ ] Create a basic project structure following Vanilla.js best practices
- [ ] Ensure landing page renders the words "Hello, World!"
- [ ] Ensure the app runs without errors

## 🌟 Resources

- [Vanilla JS Documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Introduction)
- [Web5 Documentation](https://developer.tbd.website/docs/web5/decentralized-web-nodes/access-data-with-drls)
- [Progressive Web Apps](https://web.dev/explore/progressive-web-apps)

## Getting Started

1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.
Happy coding! 🎉

### PR DESCRIPTION
**Pull request by Adjoa**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR adds a basic "Hello World" Vanilla.js app. 

## Related Tickets & Documents

Resolves #82 

## Mobile & Desktop Screenshots/Recordings

200-hello-world

## Added code snippets?
- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by blackgirlbytes** [comment]
Hi! @Adjoa Thanks for your contribution! There's a few instructions that I learned I neglected to add in the original issue. The maintainers of this repo require that you add:
- a unit test to confirm that the page renders the words Hello World
- a configuration file to include the test in our CI pipeline

@Johnnyevans32 just did a similar task with the Hello World starter but in Vue.js . You can take a look at their PR here: https://github.com/TBD54566975/tbd-examples/pull/135

Things to note:

for adding tests, it looked like this for a Vue app. We need to figure out how it will look for vanillajs -- https://github.com/Johnnyevans32/tbd-examples/blob/71f033f4e028bdc8e9efe41e8a23ce2eda0addc1/javascript/dwa-starter-vue/e2e/vue.spec.ts

for adding the config file it will look like this: https://github.com/Johnnyevans32/tbd-examples/blob/71f033f4e028bdc8e9efe41e8a23ce2eda0addc1/javascript/dwa-starter-vue/.tbd-example.json


If you need help or have questions, @leordev and @finn-tbd can provide technical assistance, but please keep in mind that the work day has ended for us, so they may not get back to you until tomorrow.

**Comment by leordev** [comment]
For the unit test I recommend using `vitest` since it's the bundler you chose! I can help you with anything you need!

**Comment by Adjoa** [comment]
Thanks @blackgirlbytes! Thanks @leordev!

**Comment by blackgirlbytes** [comment]
Hi @Adjoa! I'm just checking in. Do you need any help?

**Comment by Adjoa** [comment]
Hey @blackgirlbytes. Yes, I think so. What do you think of what I have so far?

**Comment by blackgirlbytes** [comment]
> Hey @blackgirlbytes. Yes, I think so. What do you think of what I have so far?

cool the unit test so far is fine!! the next thing we need to add is a file called `.tbd-example.json`. This will tell the test suite on how to automatically run your unit test. 
This is how one person's looks: https://github.com/Johnnyevans32/tbd-examples/blob/71f033f4e028bdc8e9efe41e8a23ce2eda0addc1/javascript/dwa-starter-vue/.tbd-example.json

Let me know if you need @leordev or I to help you figure out the contents of that file.

**Comment by blackgirlbytes** [comment]
> Hey @blackgirlbytes. Yes, I think so. What do you think of what I have so far?

cool the unit test so far is fine!! the next thing we need to add is a file called `.tbd-example.json`. This will tell the test suite on how to automatically run your unit test. 
This is how one person's looks: https://github.com/Johnnyevans32/tbd-examples/blob/71f033f4e028bdc8e9efe41e8a23ce2eda0addc1/javascript/dwa-starter-vue/.tbd-example.json

Let me know if you need @leordev or I to help you figure out the contents of that file.

**Comment by Adjoa** [comment]
@blackgirlbytes @leordev I’m glad the test looks good so far! vitest unit testing of vanilla JS is a new one for me so this is encouraging, thanks. Unfortunately, when I’m running it right now, it fails — `AssertionError: expected '' to contain 'Hello, world!’`. I’m not sure what’s missing yet. Please assist 🛟

**Comment by blackgirlbytes** [comment]
Awesome --looks like you added all the necessary files, but one of the tests are failing. I guess by the time the test runs, it's only seeing `''` instead of `'Hello, world!'`

I think if you fix that..you should be good to go!

**Comment by blackgirlbytes** [comment]
Let me toy with it a bit to see what you need to add @Adjoa

**Comment by Adjoa** [comment]
🫡 Thank you!

**Review by blackgirlbytes — APPROVED** [review]
Hey @Adjoa got the tests passing for you, but since this is not my area of specialty, I'm just going to pull in @leordev or @finn-tbd to approve this PR as well. Just to make sure the tests are right. Thank you!

**Review by leordev — APPROVED** [review]
LGTM! 🚀  Thanks for the contribution!

**Pull request merged**
