### PR TITLE
Add ARIA labels to TO DO page - Vue 

### PR DESCRIPTION
**Pull request by 29deepanshutyagi**
This PR improves the accessibility of the To-Do page in the Vue.js DWA starter by adding ARIA labels, enhancing keyboard accessibility, and ensuring compatibility with screen readers. The changes align with the goal of making the DWA more usable for individuals relying on assistive technologies.
Key Changes:

    ARIA Labels:
        Added aria-label and aria-live attributes to key interactive elements (task list, input field, checkboxes, buttons) to ensure they are descriptive and accessible to screen readers.

    Keyboard Accessibility:
        Ensured all buttons, checkboxes, and form inputs are focusable and accessible via keyboard navigation.
        Enhanced focus styles for better visual clarity during navigation.

    Task Management:
        Users can add, edit, complete, and delete tasks. When editing, the input field is pre-filled with the task title, and the button dynamically updates to reflect "Save Task."

    Screen Reader Compatibility:
        Tested the page with screen readers to ensure that all interactive elements and task-related actions are announced appropriately, improving the overall user experience for assistive technology users.
        
        
        issue #73

### CODE REVIEW

**Comment by blackgirlbytes** [comment]
hmm @29deepanshutyagi let's get #199 merged in first before you add any ARIA labels. there's a specific way that we want the to do list component to look! Thanks for the initial attempt though.

**Comment by 29deepanshutyagi** [comment]
you can tell me in what way exactly the todo list component should looks

**Comment by 29deepanshutyagi** [comment]
ok i understood

**Comment by blackgirlbytes** [comment]
@29deepanshutyagi it will not be merged. have you taken a look at the other PR? it has a lot of detail and components in it

**Pull request closed without merging**
