### PR TITLE
Create about page component - Vanilla.js

### PR DESCRIPTION
**Pull request by 29deepanshutyagi**
This PR introduces the About page component for the Decentralized Web App (DWA) starter, implemented in Vanilla.js. The new component mirrors the content and structure of the existing React implementation, providing essential information about the DWA starter and its relevance.

Changes:

    Created About component in components.js.
    Added HTML structure:
        Main title (h1): "DWA Starter Vanilla"
        Paragraph: "Decentralized Web App: it's a Web5 Progressive Web App."
        Subtitle (h2): "Why PWA?"
        Paragraph: "It's a perfect match with Web5 DWNs since a PWA can work offline and DWN has synced local storage."
    Ensured proper spacing and styling using Tailwind CSS for responsive design.
    
    
    
    
    issue #90

### CODE REVIEW

**Review by blackgirlbytes — CHANGES_REQUESTED** [review]
Awesome. Looks like the test is failing though . Let's get it to pass. Take a look here -- https://github.com/TBD54566975/tbd-examples/actions/runs/11247125645/job/31270080608?pr=233

**Comment by 29deepanshutyagi** [comment]
kindly review now

**Review by blackgirlbytes — APPROVED** [review]
Looks good! Thank you for your contribution!

**Comment by blackgirlbytes** [comment]
hi @29deepanshutyagi , it's really important to keep the PR template that's there, so you can automatically get added to the leaderboard. Please don't change it. Thank you!

**Pull request merged**
