### PR TITLE
Feat/wallet connect

### LINKED ISSUE #149: Add Wallet Connect functionality to DWA Starter App Vue
[placeholder for now]

### PR DESCRIPTION
**Pull request by Johnnyevans32**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR adds the wallet connect option for web5 connection. 

## Related Tickets & Documents

Resolves #149 

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by Johnnyevans32** [comment]
hi @leordev @blackgirlbytes, how can i test the wallet connect QR code connection, the text doesn't seem to resolve on my end

**Comment by blackgirlbytes** [comment]
Hey @Johnnyevans32 sorry about that, I was collecting information to distill for you from the engineering team. I haven't used the Wallet connect functionality myself, so I was hoping to read through the code. 

Here's the information I received so far:

- The regular OIDC/Wallet Connect flow is implemented here so they can look at this: [https://github.com/TBD54566975/tbd-examples/blob/4ee6c2e808efe28ae6529bd7b1396833b[…]5/javascript/dwa-starter-react-vite/src/web5/Web5Connection.tsx](https://github.com/TBD54566975/tbd-examples/blob/4ee6c2e808efe28ae6529bd7b1396833b729ffe5/javascript/dwa-starter-react-vite/src/web5/Web5Connection.tsx)
- They can use our react wallet or https://github.com/decentralized-identity/dweb-wallet to test their implementation.

But I'm planning to read through the code, so I can figure out the best way to write a description in a ticket for you. Hopefully, these links help for now!

**Comment by Johnnyevans32** [comment]
thank you @blackgirlbytes, tested now and it looks good cc @leordev

**Comment by leordev** [comment]
Thanks for the contribution @Johnnyevans32, you are a rockstar! 🚀 🙏 

The only issue that we found is that the wallet connection is not being persisted if you refresh the page... From the react's implementation you can see that we are automatically connecting when the homepage is accessed and you were previously connected:
- https://github.com/TBD54566975/tbd-examples/pull/111/files#diff-5b8e813f664642013d39dcc62774b713b4c101385785fa2bd564496cf1d96d32R15-R18
- https://github.com/TBD54566975/tbd-examples/pull/111/files#diff-5fa494338453a644df1516460b2094d53c88759ca3bb1cc1de720289290a870aR72 (note that this auto reconnect option does not need to build and pass the `walletConnectOptions` anymore)

**Comment by Johnnyevans32** [comment]
thank you @leordev ❤️, just added the auto connect flow now, 

just to be clear, the app auto connects using the default web5 connect option even though the user previously connected using the wallet connect option

**Review by acekyd — APPROVED** [review]

**Review by leordev — APPROVED** [review]
LGTM, great work again!!

**Pull request merged**
